spring:
  ai:
    openai:
      base-url: "https://openrouter.ai/api"

      chat:
        options:
          model: z-ai/glm-4.5-air:free         # change to any available model on OpenRouter
          temperature: 0.7

    mcp:
      client:
        stdio:

          servers-configuration: classpath:/mcp-config.json
        type: SYNC
        enabled: true
        name: "atlassian-mcp"
        version: 1.0.0



server:
  port: 8081
logging:
  level:
    org.springframework.ai.mcp: debug
    io.modelcontextprotocol.client: WARN
    io.modelcontextprotocol.spec: WARN


